import { H2HDetails } from "../types";

export const mockH2HDetails: H2HDetails[] = [
  {
    date: "2025-08-03T16:00:00Z",
    venue: {
      name: "Old Trafford",
      city: "Manchester",
    },
    leagueName: "UEFA Champions League",
    season: 2023,
    round: "Semi-Final",
    winner: "Real Madrid",
    homeHalfTimeGoal: 1,
    awayHalfTimeGoal: 1,
    homeFullTimeGoal: 2,
    awayFullTimeGoal: 1,
    homeExtraTimeGoal: 0,
    awayExtraTimeGoal: 0,
    homePenalty: 4,
    awayPenalty: 2,
  },
  {
    date: "2025-08-03T16:00:00Z",
    venue: {
      name: "Old Trafford",
      city: "Manchester",
    },
    leagueName: "UEFA Champions League",
    season: 2021,
    round: "Final",
    winner: "Real Madrid",
    homeHalfTimeGoal: 1,
    awayHalfTimeGoal: 1,
    homeFullTimeGoal: 2,
    awayFullTimeGoal: 1,
    homeExtraTimeGoal: 0,
    awayExtraTimeGoal: 0,
    homePenalty: 4,
    awayPenalty: 2,
  },
  {
    date: "2025-08-03T16:00:00Z",
    venue: {
      name: "Old Trafford",
      city: "Manchester",
    },
    leagueName: "UEFA Champions League",
    season: 2018,
    round: "Semi-Final",
    winner: "Real Madrid",
    homeHalfTimeGoal: 1,
    awayHalfTimeGoal: 1,
    homeFullTimeGoal: 2,
    awayFullTimeGoal: 1,
    homeExtraTimeGoal: 0,
    awayExtraTimeGoal: 0,
    homePenalty: 4,
    awayPenalty: 2,
  },
  {
    date: "2025-08-03T16:00:00Z",
    venue: {
      name: "Old Trafford",
      city: "Manchester",
    },
    leagueName: "UEFA Champions League",
    season: 2018,
    round: "Semi-Final",
    winner: "Real Madrid",
    homeHalfTimeGoal: 1,
    awayHalfTimeGoal: 1,
    homeFullTimeGoal: 2,
    awayFullTimeGoal: 1,
    homeExtraTimeGoal: 0,
    awayExtraTimeGoal: 0,
    homePenalty: 4,
    awayPenalty: 2,
  },
  {
    date: "2025-08-03T16:00:00Z",
    venue: {
      name: "Old Trafford",
      city: "Manchester",
    },
    leagueName: "UEFA Champions League",
    season: 2018,
    round: "Semi-Final",
    winner: "Real Madrid",
    homeHalfTimeGoal: 1,
    awayHalfTimeGoal: 1,
    homeFullTimeGoal: 2,
    awayFullTimeGoal: 1,
    homeExtraTimeGoal: 0,
    awayExtraTimeGoal: 0,
    homePenalty: 4,
    awayPenalty: 2,
  },
];
