import { LeagueRankingPlayer } from "../types";

export const mockLeagueRankingPlayers: LeagueRankingPlayer[] = [
  {
    playerId: 1,
    playerName: "Erling Haaland",
    playerPhoto: "https://example.com/photos/haaland.jpg",
    playerAge: 24,
    playerTeamId: 1,
    playerTeamLogo: "https://example.com/logos/man-city.png",
    playerTeamName: "Manchester City",
    playerTotalGoals: 28,
    playerTotalAssists: 5,
    playerTotalYellowCards: 3,
    playerTotalRedCards: 0,
    playerTotalAppearances: 32,
  },
  {
    playerId: 2,
    playerName: "Kylian Mbappé",
    playerPhoto: "https://example.com/photos/mbappe.jpg",
    playerAge: 26,
    playerTeamId: 2,
    playerTeamLogo: "https://example.com/logos/psg.png",
    playerTeamName: "Paris Saint-Germain",
    playerTotalGoals: 30,
    playerTotalAssists: 7,
    playerTotalYellowCards: 2,
    playerTotalRedCards: 0,
    playerTotalAppearances: 33,
  },
  {
    playerId: 3,
    playerName: "Jude Bellingham",
    playerPhoto: "https://example.com/photos/bellingham.jpg",
    playerAge: 22,
    playerTeamId: 3,
    playerTeamLogo: "https://example.com/logos/real-madrid.png",
    playerTeamName: "Real Madrid",
    playerTotalGoals: 18,
    playerTotalAssists: 10,
    playerTotalYellowCards: 5,
    playerTotalRedCards: 1,
    playerTotalAppearances: 29,
  },
];
