import { LiveMatchesResponse } from "../types";
import { poll } from "./polls";

export const mockLiveMatchesResponse: LiveMatchesResponse[] = [
  {
    country: "England",
    leagueMatches: [
      {
        leagueId: 39,
        leagueName: "Premier League",
        leagueCountry: "England",
        leagueLogo: "https://media.api-sports.io/football/leagues/39.png",
        matches: [
          {
            id: 101,
            homeTeamLogo: "https://media.api-sports.io/football/teams/33.png",
            awayTeamLogo: "https://media.api-sports.io/football/teams/34.png",
            homeTeamName: "Manchester United",
            homeTeamId: 23,
            awayTeamName: "Liverpool",
            awayTeamId: 24,
            homeTeamScore: 2,
            awayTeamScore: 1,
            elapsedTime: 75,
            matchDate: "2025-02-01T15:30:00Z",
            leagueName: "Premier League",
            leagueId: 2343,
            statusShort: "2H",
            statusLong: "Second Half",
            events: [
              {
                timeElapsed: 23,

                teamName: "Manchester United",
                teamLogo: "https://media.api-sports.io/football/teams/33.png",
                playerName: "Bruno Fernandes",
                eventType: "Goal",
                eventDetails: "Penalty",
              },
              {
                timeElapsed: 55,

                teamName: "Liverpool",
                teamLogo: "https://media.api-sports.io/football/teams/34.png",
                playerName: "Mohamed Salah",
                eventType: "Goal",
                eventDetails: "Normal Goal",
              },
            ],
            polls: [],
            homeAwayForm: {
              homeForm: ["W", "W", "L", "W", "W"],
              awayForm: ["L", "L", "W", "L", "L"],
              isHomeHot: true,
              isHomeCold: false,
              isAwayHot: false,
              isAwayCold: true,
              isDisplayable: true,
            },
          },
          {
            id: 102,
            homeTeamLogo: "https://media.api-sports.io/football/teams/50.png",
            awayTeamLogo: "https://media.api-sports.io/football/teams/49.png",
            homeTeamName: "Manchester City",
            homeTeamId: 324,
            awayTeamName: "Chelsea",
            awayTeamId: 532,
            homeTeamScore: 3,
            awayTeamScore: 0,
            elapsedTime: 90,
            extraTime: 2,
            leagueName: "Premier League",
            leagueId: 3457,
            statusShort: "FT",
            statusLong: "Full Time",
            matchDate: "2025-02-01T15:30:00Z",
            events: [],
            polls: [poll],
            homeAwayForm: {
              homeForm: ["W", "W", "W", "D", "W"],
              awayForm: ["L", "W", "L", "D", "L"],
              isHomeHot: true,
              isHomeCold: false,
              isAwayHot: false,
              isAwayCold: false,
              isDisplayable: true,
            },
          },
        ],
      },
    ],
  },
  {
    country: "Argentina",
    leagueMatches: [
      {
        leagueId: 128,
        leagueName: "Liga Profesional de Fútbol",
        leagueCountry: "Argentina",
        leagueLogo: "https://media.api-sports.io/football/leagues/39.png",
        matches: [
          {
            id: 123,
            homeTeamLogo: "https://media.api-sports.io/football/teams/33.png",
            awayTeamLogo: "https://media.api-sports.io/football/teams/34.png",
            homeTeamName: "Manchester United",
            homeTeamId: 785,
            awayTeamName: "Liverpool",
            awayTeamId: 975,
            homeTeamScore: 2,
            awayTeamScore: 1,
            elapsedTime: 75,

            leagueName: "Premier League",
            leagueId: 346,
            statusShort: "2H",
            statusLong: "Second Half",
            matchDate: "2025-02-01T15:30:00Z",
            events: [
              {
                timeElapsed: 23,

                teamName: "Manchester United",
                teamLogo: "https://media.api-sports.io/football/teams/33.png",
                playerName: "Bruno Fernandes",
                eventType: "Goal",
                eventDetails: "Penalty",
              },
              {
                timeElapsed: 55,

                teamName: "Liverpool",
                teamLogo: "https://media.api-sports.io/football/teams/34.png",
                playerName: "Mohamed Salah",
                eventType: "Goal",
                eventDetails: "Normal Goal",
              },
            ],
            polls: [poll],
            homeAwayForm: {
              homeForm: ["D", "W", "L", "W", "D"],
              awayForm: ["W", "D", "W", "L", "W"],
              isHomeHot: false,
              isHomeCold: false,
              isAwayHot: false,
              isAwayCold: false,
              isDisplayable: true,
            },
          },
          {
            id: 1232,
            homeTeamLogo: "https://media.api-sports.io/football/teams/50.png",
            awayTeamLogo: "https://media.api-sports.io/football/teams/49.png",
            homeTeamName: "Manchester City",
            homeTeamId: 546,
            awayTeamName: "Chelsea",
            awayTeamId: 123,
            homeTeamScore: 3,
            awayTeamScore: 0,
            elapsedTime: 90,
            extraTime: 2,
            leagueName: "Premier League",
            leagueId: 986,
            statusShort: "FT",
            statusLong: "Full Time",
            matchDate: "2025-02-01T15:30:00Z",
            events: [],
            polls: [],
            homeAwayForm: {
              homeForm: ["L", "L", "L", "D", "W"],
              awayForm: ["W", "W", "W", "D", "L"],
              isHomeHot: false,
              isHomeCold: false,
              isAwayHot: false,
              isAwayCold: false,
              isDisplayable: true,
            },
          },
        ],
      },
      {
        leagueId: 1232,
        leagueName: "La Copa",
        leagueCountry: "Argentina",
        leagueLogo: "https://media.api-sports.io/football/leagues/128.png",
        matches: [
          {
            id: 123,
            homeTeamLogo: "https://media.api-sports.io/football/teams/33.png",
            awayTeamLogo: "https://media.api-sports.io/football/teams/34.png",
            homeTeamName: "Manchester United",
            homeTeamId: 55,

            awayTeamName: "Liverpool",
            awayTeamId: 454,
            homeTeamScore: 2,
            awayTeamScore: 1,
            elapsedTime: 75,
            matchDate: "2025-02-01T15:30:00Z",
            leagueName: "Premier League",
            leagueId: 435,
            statusShort: "2H",
            statusLong: "Second Half",
            events: [
              {
                timeElapsed: 23,

                teamName: "Manchester United",
                teamLogo: "https://media.api-sports.io/football/teams/435.png",
                playerName: "Bruno Fernandes",
                eventType: "Goal",
                eventDetails: "Penalty",
              },
              {
                timeElapsed: 55,

                teamName: "Liverpool",
                teamLogo: "https://media.api-sports.io/football/teams/334.png",
                playerName: "Mohamed Salah",
                eventType: "Goal",
                eventDetails: "Normal Goal",
              },
            ],
            polls: [poll],
            homeAwayForm: {
              homeForm: ["W", "D", "W", "W", "L"],
              awayForm: ["L", "W", "D", "L", "W"],
              isHomeHot: false,
              isHomeCold: false,
              isAwayHot: false,
              isAwayCold: false,
              isDisplayable: true,
            },
          },
        ],
      },
    ],
  },
];
