import { TeamDetails, PlayerSummary } from "../types";

export const players: PlayerSummary[] = [
  {
    name: "Liam Johnson",
    age: 24,
    height: "6'1",
    weight: "180 lbs",
    position: "Forward",
    goals: 15,
    yellowCards: 3,
    redCards: 0,
    penaltiesSaved: 0,
    penaltiesScored: 4,
  },
  {
    name: "Ethan Smith",
    age: 29,
    height: "5'10",
    weight: "165 lbs",
    position: "Midfielder",
    goals: 7,
    yellowCards: 5,
    redCards: 1,
    penaltiesSaved: 0,
    penaltiesScored: 2,
  },
  {
    name: "Noah Brown",
    age: 22,
    height: "6'0",
    weight: "175 lbs",
    position: "Defender",
    goals: 2,
    yellowCards: 6,
    redCards: 0,
    penaltiesSaved: 0,
    penaltiesScored: 0,
  },
  {
    name: "Oliver Davis",
    age: 27,
    height: "5'11",
    weight: "170 lbs",
    position: "Goalkeeper",
    goals: 0,
    yellowCards: 1,
    redCards: 0,
    penaltiesSaved: 5,
    penaltiesScored: 0,
  },
  {
    name: "Lucas Martinez",
    age: 25,
    height: "6'2",
    weight: "185 lbs",
    position: "Forward",
    goals: 20,
    yellowCards: 4,
    redCards: 1,
    penaltiesSaved: 0,
    penaltiesScored: 6,
  },
  {
    name: "Mason Wilson",
    age: 30,
    height: "5'9",
    weight: "160 lbs",
    position: "Midfielder",
    goals: 5,
    yellowCards: 7,
    redCards: 0,
    penaltiesSaved: 0,
    penaltiesScored: 1,
  },
  {
    name: "James Anderson",
    age: 28,
    height: "6'0",
    weight: "178 lbs",
    position: "Defender",
    goals: 3,
    yellowCards: 2,
    redCards: 0,
    penaltiesSaved: 0,
    penaltiesScored: 0,
  },
  {
    name: "Benjamin Taylor",
    age: 23,
    height: "5'11\"",
    weight: "172 lbs",
    position: "Forward",
    goals: 12,
    yellowCards: 3,
    redCards: 0,
    penaltiesSaved: 0,
    penaltiesScored: 3,
  },
  {
    name: "Alexander Thomas",
    age: 26,
    height: "6'1\"",
    weight: "180 lbs",
    position: "Midfielder",
    goals: 8,
    yellowCards: 4,
    redCards: 1,
    penaltiesSaved: 0,
    penaltiesScored: 2,
  },
  {
    name: "William Moore",
    age: 31,
    height: "6'2\"",
    weight: "190 lbs",
    position: "Goalkeeper",
    goals: 0,
    yellowCards: 1,
    redCards: 0,
    penaltiesSaved: 6,
    penaltiesScored: 0,
  },
];

export const teamDetails: TeamDetails = {
  teamName: "Newcastle",
  teamLogo: "",
  teamCountry: "England",
  teamFounded: 1892,
  venueName: "St. James' Park",
  venueCity: "Newcastle upon Tyne",
  venueCapacity: 52758,
  coachName: "E. Howe",
  coachAge: 48,
  videos: [{ url: "https://www.youtube.com/watch?v=team1", esLabel: "Resumen del Equipo", enLabel: "Team Highlights", uploadDate: "01/01/2026" }],
};
