import { TeamFixture } from "../types";

export const mockTeamFixture: TeamFixture = {
  previous: [
    {
      fixtureId: 1,
      date: "2025-09-15T19:45:00Z",
      homeTeamId: 101,
      awayTeamId: 202,
      homeTeamName: "Manchester United",
      awayTeamName: "Liverpool",
      homeTeamLogo: "https://example.com/logos/manutd.png",
      awayTeamLogo: "https://example.com/logos/liverpool.png",
      homeTeamScore: 1,
      awayTeamScore: 3,
      isFinished: true,
      statusLong: "NOT STARTED",
      statusShort: "NS",
      isLiveNow: true,
    },
    {
      fixtureId: 2,
      date: "2025-09-10T17:30:00Z",
      homeTeamId: 303,
      awayTeamId: 101,
      homeTeamName: "Chelsea",
      awayTeamName: "Manchester United",
      homeTeamLogo: "https://example.com/logos/chelsea.png",
      awayTeamLogo: "https://example.com/logos/manutd.png",
      homeTeamScore: 2,
      awayTeamScore: 1,
      isFinished: true,
      statusLong: "FULL TIM",
      statusShort: "FT",
      isLiveNow: false,
    },
  ],
  upcoming: [
    {
      fixtureId: 3,
      date: "2025-09-25T20:00:00Z",
      homeTeamId: 101,
      awayTeamId: 404,
      homeTeamName: "Manchester United",
      awayTeamName: "Arsenal",
      homeTeamLogo: "https://example.com/logos/manutd.png",
      awayTeamLogo: "https://example.com/logos/arsenal.png",
      isFinished: false,
      statusLong: "NOT STARTED",
      statusShort: "NS",
      isLiveNow: false,
    },
    {
      fixtureId: 4,
      date: "2025-09-30T18:00:00Z",
      homeTeamId: 505,
      awayTeamId: 101,
      homeTeamName: "Tottenham",
      awayTeamName: "Manchester United",
      homeTeamLogo: "https://example.com/logos/tottenham.png",
      awayTeamLogo: "https://example.com/logos/manutd.png",
      isFinished: false,
      statusLong: "FULL TIME",
      statusShort: "FT",
      isLiveNow: true,
    },
  ],
};
